const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const renderer = path.join(root, 'renderer');
const requiredFiles = ['motion.html', 'unified.css', 'live.css', 'conversation-store.js', 'composer-behavior.js', 'response-stream.js', 'auto-speech.js', 'markdown-renderer.js', 'unified.js', 'hologram.js'];
assert.ok(fs.statSync(path.join(root, 'runtime-settings.cjs')).isFile(), 'missing runtime settings module');
assert.ok(fs.statSync(path.join(root, 'update-checker.cjs')).isFile(), 'missing update checker module');

for (const file of requiredFiles) {
  assert.ok(fs.statSync(path.join(renderer, file)).isFile(), `missing renderer resource: ${file}`);
}

const html = fs.readFileSync(path.join(renderer, 'motion.html'), 'utf8');
const main = fs.readFileSync(path.join(root, 'main.cjs'), 'utf8');
const updateChecker = fs.readFileSync(path.join(root, 'update-checker.cjs'), 'utf8');
const supervisor = fs.readFileSync(path.join(root, 'core-supervisor.cjs'), 'utf8');
const preload = fs.readFileSync(path.join(root, 'preload.cjs'), 'utf8');
const bridge = fs.readFileSync(path.join(root, 'core-bridge.cjs'), 'utf8');
const unified = fs.readFileSync(path.join(renderer, 'unified.js'), 'utf8');
const liveCss = fs.readFileSync(path.join(renderer, 'live.css'), 'utf8');
const unifiedCss = fs.readFileSync(path.join(renderer, 'unified.css'), 'utf8');
const conversationStore = fs.readFileSync(path.join(renderer, 'conversation-store.js'), 'utf8');
const composerBehavior = fs.readFileSync(path.join(renderer, 'composer-behavior.js'), 'utf8');
const autoSpeech = fs.readFileSync(path.join(renderer, 'auto-speech.js'), 'utf8');
const responseStream = fs.readFileSync(path.join(renderer, 'response-stream.js'), 'utf8');
const markdownRenderer = fs.readFileSync(path.join(renderer, 'markdown-renderer.js'), 'utf8');
const hologram = fs.readFileSync(path.join(renderer, 'hologram.js'), 'utf8');
const syncAiControlsMatch = unified.match(/const syncAiConnectionControls = \(mode = [\s\S]*?\) => \{([\s\S]*?)\n\};/);
assert.ok(syncAiControlsMatch, 'AI connection control synchronizer must be defined');
assert.match(syncAiControlsMatch[1], /apiKeyInputControl\) apiKeyInputControl\.hidden = !directMode/);
assert.match(syncAiControlsMatch[1], /apiConnectControl\) apiConnectControl\.hidden = !directMode/);
assert.match(syncAiControlsMatch[1], /directProviderRow\) directProviderRow\.hidden = !directMode/);
assert.doesNotMatch(syncAiControlsMatch[1], /syncAiConnectionControls\s*\(/, 'AI connection control synchronizer must not recursively invoke itself');
const chatStart = html.indexOf('<section class="chat-pane');
const coreStart = html.indexOf('<main class="workspace');
const coreSpaceEnd = html.indexOf('<span id="quality"', coreStart);
const monitorStart = html.indexOf('<aside class="system-monitor-card');
const dockStackStart = html.indexOf('<div class="dock-stack">');
const inspectStart = html.indexOf('<section id="inspect-panel"');
assert.ok(chatStart >= 0 && coreStart > chatStart, 'chat card should precede the Core layer');
assert.ok(monitorStart > chatStart && monitorStart < coreStart, 'monitor card should sit below Chat and outside the Core layer');
assert.ok(coreSpaceEnd > coreStart && dockStackStart > coreStart && inspectStart > dockStackStart, 'Core and Pages stacks should remain after the left card stack');
assert.match(html.slice(chatStart, coreStart), /<\/section>\s*<\/section>\s*<aside class="system-monitor-card/, 'monitor card should follow the Chat card');
assert.match(html, /class="dock-stack">[\s\S]*id="inspect-panel"[\s\S]*<\/section>\s*<\/div>/);
const chatMarkup = html.slice(chatStart, monitorStart);
assert.match(html, /href="unified\.css"/);
assert.match(html, /href="live\.css"/);
assert.match(html, /src="hologram\.js"/);
assert.match(html, /src="conversation-store\.js"/);
assert.match(html, /src="auto-speech\.js"/);
assert.match(html, /src="response-stream\.js"/);
assert.match(html, /src="markdown-renderer\.js"/);
assert.match(html, /src="unified\.js"/);
assert.match(html, /Content-Security-Policy/);
assert.match(html, /script-src 'self'/);
assert.match(html, /style-src 'self' 'unsafe-inline'/);
assert.match(html, /connect-src 'none'/);
assert.match(html, /id="messages"/);
assert.match(html, /class="chat-pane(?:\s|\")/);
assert.doesNotMatch(html, /<aside[^>]*class="chat-pane"/);
assert.match(html, /class="core-stage"/);
assert.match(html, /class="dock-zone(?:\s|\")/);
assert.match(html, /class="dock-zone card-layer pages-collapsed"/);
assert.doesNotMatch(html, /<aside[^>]*class="dock-zone"/);
assert.match(html, /class="dock-stack"/);
assert.match(html, /class="action-dock"/);
assert.match(html, /id="pages-toggle"[^>]*aria-expanded="false"[^>]*aria-label="Expand Feature"/);
assert.match(html, /class="pages-toggle-label">Feature<\/span>/);
assert.match(html, /class="dock-head"><span class="caption">Feature<\/span>/);
assert.match(html, /id="pages-panel-toggle"[^>]*aria-expanded="false"[^>]*aria-label="Show Feature"/);
assert.equal((html.match(/class="nav-label"/g) || []).length, 18, 'Pages launcher should keep one visible label per page button');
assert.match(html, /data-page="history"[^>]*aria-label="Chat history"[^>]*title="Chat history"/);
assert.match(html, /id="view-history"[^>]*aria-label="Chat history"/);
assert.match(html, /id="conversation-list"/);
assert.match(html, /id="history-refresh"/);
assert.match(html, /id="history-new"[^>]*>Start new chat/);
assert.match(html, /class="subhead history-subhead"/);
assert.match(html, /class="instrument-actions history-actions"/);
assert.match(html, /class="instrument-actions voice-actions" aria-label="Voice actions"/);
assert.match(html, /id="conversations-status"[^>]*class="settings-status history-status"/);
assert.match(html, /data-page="core"[^>]*aria-label="Core connection"[^>]*title="Core connection"/);
assert.match(html, /id="view-core"[^>]*aria-label="Core connection"/);
assert.match(html, /id="core-refresh"[^>]*>Refresh<\//);
assert.match(html, /id="core-reconnect"[^>]*>Reconnect Core<\//);
assert.match(html, /class="subhead core-subhead"[\s\S]*class="instrument-actions core-actions"[^>]*aria-label="Core connection controls"/);
assert.doesNotMatch(html, /class="subhead history-subhead core-subhead"/);
assert.match(html, /id="core-connection-state"/);
assert.match(html, /id="core-connection-checked"/);
assert.match(html, /id="core-connection-status"[^>]*role="status"/);
assert.match(html, /id="background-running-setting"[^>]*type="checkbox"/);
assert.match(html, /id="start-on-login-setting"[^>]*type="checkbox"/);
assert.match(html, /id="runtime-settings-status"[^>]*role="status"/);
assert.match(html, /id="update-check"[^>]*>Check now<\//);
assert.match(html, /id="update-status"[^>]*role="status"/);
assert.match(html, /data-page="knowledge"[\s\S]*class="nav-label">Knowledge<\/span>/);
assert.match(html, /id="inspect-panel"[^>]*hidden/);
assert.match(html, /class="local-clock"/);
assert.match(html, /id="local-time"/);
assert.match(html, /id="local-date"/);
assert.match(html, /id="update-notice"[^>]*hidden[^>]*role="status"/);
assert.match(html, /id="update-notice-title"/);
assert.match(html, /id="update-notice-detail"/);
assert.match(html, /id="update-open"[^>]*>Download update<\//);
assert.match(html, /id="update-dismiss"[^>]*>Later<\//);
assert.doesNotMatch(html, /ASSISTANT\s*·\s*LIVE CHAT/i);
assert.doesNotMatch(html, /<h1>Local conversation<\/h1>/i);
assert.doesNotMatch(html, /Local motion remains visible while the workspace is inspected/i);
assert.doesNotMatch(html, /id="runtime-note"/i);
assert.doesNotMatch(html, /id="new"/);
assert.doesNotMatch(html, /New conversation/i);
assert.match(html, /class="chat-pane card-layer"/);
assert.match(html, /class="workspace core-layer"/);
assert.doesNotMatch(html, /class="chat-status"/);
assert.doesNotMatch(chatMarkup, /system-runtime|core-status|ai-status|connection-value|model-value/);
assert.doesNotMatch(html, /class="core-head"/);
assert.doesNotMatch(html, /id="assistant-note"/);
assert.match(html, /id="close-panel"/);
assert.doesNotMatch(html, /data-page="monitor"/);
assert.doesNotMatch(html, /id="view-monitor"/);
assert.match(html, /data-page="settings"[^>]*aria-label="Settings"[^>]*title="Settings"/);
const tasksNavButton = html.match(/<button data-page="tasks"[\s\S]*?<\/button>/)?.[0] || '';
const toolsNavButton = html.match(/<button data-page="tools"[\s\S]*?<\/button>/)?.[0] || '';
assert.doesNotMatch(tasksNavButton, /<small>/, 'Tasks navigation must not carry a static sample count');
assert.doesNotMatch(toolsNavButton, /<small>/, 'Tools navigation must not carry a static sample count');
assert.match(html, /id="view-settings"[^>]*aria-label="Settings"/);
assert.match(html, /id="locale-setting"[^>]*aria-label="Date language"/);
assert.match(html, /id="locale-status"[^>]*role="status"/);
assert.match(html, /id="response-language-setting"[^>]*aria-label="Response language"/);
assert.match(html, /value="en">English<\/option>[\s\S]*value="zh-CN">中文<\/option>/);
assert.match(html, /id="response-language-status"[^>]*role="status"/);
assert.match(html, /data-page="memory"[^>]*aria-label="Memory"[^>]*title="Memory"/);
assert.match(html, /data-page="knowledge"[^>]*aria-label="Knowledge"[^>]*title="Knowledge"/);
assert.match(html, /id="view-memory"[^>]*aria-label="Memory"/);
assert.match(html, /id="view-knowledge"[^>]*aria-label="Knowledge"/);
assert.match(html, /<div class="caption gold">MEMORY<\/div>/);
assert.match(html, /<div class="caption gold">KNOWLEDGE<\/div>/);
assert.match(html, /Conversation history/);
assert.match(html, /Obsidian vaults/);
assert.match(html, /id="history-list"/);
assert.match(html, /id="vault-list"/);
assert.match(html, /id="memory-refresh"/);
assert.match(html, /id="knowledge-refresh"[^>]*title="Check Obsidian registration"[^>]*>Refresh connection/);
assert.match(html, /id="obsidian-connection-actions"[^>]*aria-label="Obsidian connection controls"/);
assert.match(html, /id="obsidian-vault-name"[^>]*maxlength="200"/);
assert.match(html, /id="obsidian-vault-path"[^>]*maxlength="1000"/);
assert.match(html, /id="obsidian-connect"[^>]*>Connect \/ reconnect Obsidian/);
assert.match(html, /id="obsidian-connection-status"[^>]*role="status"/);
assert.match(html, /data-page="theme"[^>]*aria-label="Theme"[^>]*title="Theme"/);
assert.match(html, /id="view-theme"[^>]*aria-label="Theme"/);
assert.match(html, /VISUAL SYSTEM · THEME/);
assert.match(html, /id="theme-setting"[^>]*aria-label="Visual theme"/);
assert.match(html, /value="amber">Amber Core/);
assert.match(html, /value="cyan">Cyan Circuit/);
assert.match(html, /value="violet">Violet Pulse/);
assert.match(html, /value="matrix">Matrix Green/);
assert.match(html, /id="theme-status"[^>]*role="status"/);
assert.match(html, /id="theme-reset-custom"[^>]*>Reset custom<\/button>/);
assert.equal((html.match(/data-theme-color=/g) || []).length, 8, 'Theme should expose eight custom color controls');
assert.match(html, /id="theme-color-background"[^>]*type="color"/);
assert.match(html, /id="theme-color-border"[^>]*type="color"/);
assert.match(html, /id="theme-color-text"[^>]*type="color"/);
assert.match(html, /id="theme-color-core-a"[^>]*type="color"/);
assert.match(html, /id="theme-custom-status"[^>]*role="status"/);
const settingsStart = html.indexOf('<section id="view-settings"');
const memoryViewStart = html.indexOf('<section id="view-memory"');
const knowledgeViewStart = html.indexOf('<section id="view-knowledge"');
const themeViewStart = html.indexOf('<section id="view-theme"');
assert.ok(settingsStart >= 0 && memoryViewStart > settingsStart && knowledgeViewStart > memoryViewStart && themeViewStart > knowledgeViewStart, 'memory and knowledge pages should have stable inspector order');
assert.doesNotMatch(html.slice(settingsStart, memoryViewStart), /theme-setting|theme-status/);
assert.match(html.slice(memoryViewStart, knowledgeViewStart), /history-list/);
assert.doesNotMatch(html.slice(memoryViewStart, knowledgeViewStart), /vault-list/);
assert.match(html.slice(knowledgeViewStart, themeViewStart), /vault-list/);
assert.doesNotMatch(html.slice(knowledgeViewStart, themeViewStart), /history-list/);
assert.match(html.slice(themeViewStart), /id="theme-setting"/);
assert.match(html, /id="auto-speak-setting"[^>]*type="checkbox"/);
assert.doesNotMatch(html, /id="auto-speak-setting"[^>]*checked/);
assert.match(html, /id="auto-speak-status"[^>]*role="status"/);
assert.match(html, /id="panel-idle-setting"[^>]*aria-label="Floating panel auto-close"/);
assert.match(html, /value="5">5 seconds/);
assert.match(html, /value="10">10 seconds/);
assert.match(html, /value="25">25 seconds/);
assert.match(html, /value="30">30 seconds/);
assert.match(html, /value="60">60 seconds/);
assert.match(html, /value="0">Never/);
assert.match(html, /id="panel-idle-status"[^>]*role="status"/);
assert.match(html, /Scrolling the panel counts as activity/);
assert.match(html, /No per-message read buttons are used/);
assert.doesNotMatch(html, /Read reply|Stop reading/i);
assert.match(html, /id="tasks-refresh"/);
assert.match(html, /id="task-list"/);
assert.match(html, /id="tool-results-list"/);
assert.match(html, /id="system-info-result"/);
assert.match(html, /id="device-battery-remaining-capacity"/);
assert.match(html, /id="device-battery-cycle-count"/);
assert.match(html, /Battery diagnostics/);
assert.match(html, /data-page="working-context"[^>]*aria-label="Working context \(developer\)"/);
assert.match(html, /id="view-working-context"/);
assert.match(html, /Registered projects and safe inspection\./);
assert.match(html, /Project context is not automatically sent with every chat message\./);
assert.match(html, /id="view-context"[^>]*class="view panel-view"[\s\S]*?Read-only device information\./);
assert.match(html, /id="project-list"/);
assert.match(html, /id="projects-rescan"/);
assert.match(html, /id="ai-mode-setting"/);
assert.match(html, /id="ai-connection-state"[^>]*aria-live="polite"/);
assert.match(html, /id="ai-connection-actions"/);
assert.match(html, /data-page="usage"[^>]*aria-label="Token usage"/);
assert.match(html, /id="view-usage"[^>]*class="view panel-view"[^>]*aria-label="Token usage"/);
assert.match(html, /id="token-usage-card"[^>]*class="token-usage-card token-usage-preview"/);
assert.match(html, /id="token-usage-card"[^>]*aria-label="JARVIS token usage preview"/);
assert.match(html, /class="caption gold">JARVIS USAGE<\/span>/);
assert.match(html, /id="token-usage-total"/);
assert.match(html, /id="token-usage-input"/);
assert.match(html, /id="token-usage-output"/);
assert.doesNotMatch(html, /id="token-usage-heatmap"/, 'Core-stage widget should not include an account/activity heatmap');
assert.doesNotMatch(html, /id="token-usage-chart"/, 'Core-stage widget should not include a trend chart');
assert.match(html, /id="token-usage-status"[^>]*role="status"/);
assert.doesNotMatch(html, /id="token-usage-close"/, 'Token Usage widget should not expose a close button');
assert.match(html, /class="core-space">[\s\S]*<\/div>\s*<aside id="token-usage-card"[^>]*class="token-usage-card token-usage-preview"/, 'Token preview should live in the Core stage widget slot, outside the canvas space');
assert.match(unifiedCss, /\.core-space \{[\s\S]*top: 50%;[\s\S]*height: var\(--core-height\);[\s\S]*transform: translateY\(-50%\);/, 'Core canvas should use a centered stage slot independent of the token widget');
assert.match(unifiedCss, /\.token-usage-card \{[\s\S]*top: var\(--floating-top\);[\s\S]*width: min\(360px, calc\(100vw - 40px\)\);[\s\S]*max-height: none;[\s\S]*overflow: visible;/, 'Token preview should share the floating card top anchor and remain non-scrolling');
assert.match(unifiedCss, /\.token-usage-preview \.token-usage-stats \{ display: grid; margin-top: 10px; \}/, 'Token preview should expose the compact JARVIS summary');
assert.match(unifiedCss, /\.token-usage-preview \.token-usage-status \{ display: block;/, 'Token preview should expose its local source status');
assert.doesNotMatch(unifiedCss, /\.token-usage-preview \.token-usage-chart/, 'Token preview should not style or expose a trend chart');
assert.match(html, /id="token-usage-page-total"/);
assert.match(html, /id="token-usage-page-input"/);
assert.match(html, /id="token-usage-page-output"/);
assert.match(html, /id="token-usage-page-heatmap"[^>]*role="img"/);
assert.match(html, /id="token-usage-page-chart"[^>]*class="token-usage-chart"/);
assert.match(html, /id="token-usage-page-status"[^>]*role="status"/);
assert.match(html, /id="usage-live-badge"[^>]*class="usage-live-badge"/);
assert.match(html, /id="usage-refresh"[^>]*>Refresh usage<\//);
assert.match(unified, /rendererAccountUsageStorageKey/);
assert.match(unified, /function normalizeAccountUsageSnapshot\(response\)/);
assert.match(unified, /function refreshAccountUsage\(\{ manual = false \} = \{\}\)/);
assert.match(unified, /coreBridge\.aiUsage/);
assert.match(unified, /function usageRecordsForDisplay\(\)/);
assert.match(unified, /ChatGPT account usage unavailable/);
assert.match(preload, /aiUsage: 'jarvis-core-ai-usage'/);
assert.match(preload, /aiUsage: \(\) => invoke\(channels\.aiUsage\)/);
assert.match(main, /ipcMain\.handle\('jarvis-core-ai-usage'/);
assert.match(bridge, /aiUsage: Object\.freeze\(\{ method: 'GET', path: '\/api\/settings\/ai\/usage'/);
assert.match(html, /id="ai-reconnect"[^>]*title="Check or reconnect the selected ChatGPT subscription"[^>]*>Refresh connection</);
assert.match(html, /id="ai-disconnect"[^>]*>Disconnect AI</);
assert.match(html, /id="ai-direct-provider"/);
assert.match(html, /Google Gemini · Interactions API/);
assert.match(html, /DeepSeek · Chat Completions/);
assert.match(html, /id="ai-direct-model"/);
assert.match(html, /id="ai-direct-base-url"/);
assert.match(html, /id="ai-direct-api-key"[^>]*type="password"/);
assert.match(html, /id="ai-api-connect"[^>]*>Connect selected provider</);
assert.match(html, /id="ai-compatible-models"[^>]*hidden/);
assert.match(html, /id="ai-compatible-model-list"/);
assert.ok(html.indexOf('id="ai-connection-actions"') < html.indexOf('<script src="unified.js"'), 'AI connection controls must exist before unified.js initializes');
assert.match(unifiedCss, /\.connection-actions \{ display: grid; grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(unifiedCss, /\.connection-actions \{[^}]*column-gap: 10px; row-gap: 12px; margin-top: 16px;/);
assert.match(unifiedCss, /\.connection-actions input \{ grid-column: 1 \/ -1;/);
assert.match(unifiedCss, /\.connection-actions \.button \{[^}]*overflow-wrap: anywhere;[^}]*white-space: normal;/);
assert.match(unifiedCss, /#ai-connection-status \{ margin-top: 18px; padding-top: 1px; line-height: 1\.6; \}/);
assert.match(unifiedCss, /\.core-subhead \{ display: block; margin-bottom: 0; \}/);
assert.match(unifiedCss, /\.core-actions \{ width: 100%; justify-content: flex-start; gap: 10px; margin-top: 16px; \}/);
assert.match(unifiedCss, /\.core-actions \.button \{ min-width: 118px; \}/);
assert.match(unifiedCss, /\.model-chip-list \{ display: flex; flex-wrap: wrap;/);
assert.match(unified, /ai\.user_disconnected === true/);
assert.match(unified, /snapshot\?\.ai\?\.user_disconnected !== true/);
assert.match(unified, /let latestAiModeRequest = 0;/);
assert.match(unified, /const directProviderInfo = Object\.freeze/);
assert.match(unified, /let directProviderDraftDirty = false;/);
assert.match(unified, /let directModelDraftDirty = false;/);
assert.match(unified, /const canAdoptCoreDirectConfig = !directProviderDraftDirty && !directModelDraftDirty;/);
assert.match(unified, /directProviderDraftDirty = true;/);
assert.match(unified, /directModelControl\?\.addEventListener\('input'/);
assert.match(unified, /usage: \['Token usage', 'Account usage is separate from connection state.'/);
assert.match(unified, /function toggleTokenUsageCard\(force = null\)/);
assert.match(unified, /showTokenUsageCard\(\{ animate: false \}\);/);
assert.match(unified, /recordTokenUsage\(response, turn\);/);
assert.match(unified, /rendererUsageStorageKey/);
assert.match(unified, /const jarvisRecords = tokenUsageRecords;/);
assert.match(unified, /formatTokenUsageK\(jarvisTotal\)/);
assert.match(unified, /No JARVIS provider-reported usage yet/);
assert.doesNotMatch(unified, /renderTokenUsageHeatmap\('#token-usage-heatmap'\)/);
assert.doesNotMatch(unified, /renderTokenUsageChart\('#token-usage-chart'\)/);
assert.match(unified, /function renderTokenUsageChart\(target = '#token-usage-chart'\)/);
assert.match(unified, /token-usage-page-chart/);
assert.match(unified, /createUsageSvgElement/);
assert.match(unified, /function formatTokenUsageK\(value\)/);
assert.match(unified, /usage-y-label/);
assert.match(unified, /usage-tick/);
assert.match(unified, /usage-point/);
assert.match(unified, /usage-tooltip/);
assert.match(unified, /X axis by date/);
assert.match(unified, /focus a point for its date and value/);
assert.match(unified, /const internalTestPages = new Set\(\[\n  'assistant', 'history', 'core', 'tools', 'context', 'connections'/);
assert.match(unified, /edition === 'internal-test' && !internalTestPages\.has\(page\)/);
assert.match(unified, /if \(edition === 'internal-test'\) \{[\s\S]*?if \(!internalTestPages\.has\(button\.dataset\.page\)\) button\.hidden = true;/);
assert.doesNotMatch(unified, /developerOnlyPages/);
assert.match(unified, /const directCompatibleModelList = \$\('#ai-compatible-model-list'\)/);
assert.match(unified, /gpt-5\.6-sol/);
assert.match(unified, /gemini-3\.8-flash/);
assert.match(unified, /deepseek-v4-pro/);
assert.match(unified, /No fixed model list: use only an ID listed by this gateway/);
assert.match(unified, /coreBridge\.aiDirectConfig/);
assert.match(unified, /function formatCoreHealthTime\(\)/);
assert.match(unified, /setCoreHealthCheck\('checking…'\)/);
assert.match(unified, /setCoreHealthCheck\(formatCoreHealthTime\(\)\)/);
assert.match(unified, /if \(requestId !== latestAiModeRequest\) return;/);
assert.match(unified, /if \(mode === 'managed_subscription'\) \{[\s\S]*?if \(coreOnline\) void refreshAccountUsage\(\);/);
assert.match(unified, /function motionIsReduced\(\)/);
assert.match(unified, /let pagesNavigationExpanded = false;/);
assert.match(unified, /function syncPagesNavigation\(\)/);
assert.match(unified, /function setPagesNavigationExpanded\(expanded\)/);
assert.match(unified, /setPagesNavigationExpanded\(false\);/);
assert.match(unified, /#pages-toggle/);
assert.match(unified, /#pages-panel-toggle/);
assert.match(unified, /const settingsPageButton = pagesNav\?\.querySelector\('\[data-page="settings"\]'\)/);
assert.match(unified, /pagesNav\.append\(settingsPageButton\)/);
assert.match(unified, /function animatePageView\(view\)/);
assert.match(unified, /page-view-enter/);
assert.match(unified, /page-header-enter/);
assert.match(unified, /cancelPageViewTransition\(\)[\s\S]*inspect-head\.page-header-enter/);
assert.match(unified, /let featureTransitionToken = 0/);
assert.match(unified, /function cancelFeatureTransition\(\)/);
assert.match(unified, /function animateFeatureSurface\(kind\)/);
assert.match(unified, /getAnimations\?\.\(\)\.forEach/);
assert.match(unified, /animationcancel/);
assert.match(unified, /if \(pagesNavigationExpanded\) animateFeatureSurface\('navigation'\)/);
assert.match(unified, /animateFeatureSurface\('page'\)/);
assert.match(unified, /feature-nav-enter/);
assert.match(unified, /feature-page-enter/);
assert.match(unified, /return lowMotionPreference === true;/);
assert.match(unified, /function animateConversationRestore\(\)/);
assert.match(unified, /conversation-restore/);
assert.match(unified, /openStoredConversation\(conversation\.id, open\)/);
assert.match(unified, /trigger\?\.closest\('\.conversation-row'\)/);
assert.doesNotMatch(unified, /event\.currentTarget\.disabled = true;/, 'AI transport selector must remain operable while a previous mode request finishes');
assert.match(html, /id="speech-settings-value"/);
assert.match(html, /id="view-voice"[^>]*aria-label="Voice"/);
assert.match(html, /id="voice-package-setting"[^>]*aria-label="Windows voice package"/);
assert.match(html, /id="voice-refresh"[^>]*>Refresh voices<\//);
assert.match(html, /id="voice-test"[^>]*>Test voice<\//);
assert.match(html, /id="voice-auto-speech-setting"[^>]*type="checkbox"/);
assert.match(html, /id="voice-package-status"[^>]*role="status"/);
assert.match(html, /id="low-motion-setting"[^>]*type="checkbox"/);
assert.match(html, /id="motion-status"[^>]*role="status"/);
assert.match(html, /id="event-list"/);
assert.match(html, /data-page="events"[^>]*aria-label="Events"[^>]*title="Events"/);
assert.match(html, /data-page="errors"[^>]*aria-label="Errors"[^>]*title="Errors"/);
assert.match(html, /id="view-events"[^>]*aria-label="Events"/);
assert.match(html, /id="view-errors"[^>]*aria-label="Errors"/);
assert.match(html, /<div class="caption gold">EVENTS<\/div>/);
assert.match(html, /<div class="caption gold">ERRORS<\/div>/);
assert.match(html, /id="events-clear"[^>]*>Clear events<\//);
assert.match(html, /id="errors-clear"[^>]*>Clear errors<\//);
assert.match(html, /id="error-list"/);
const eventsViewStart = html.indexOf('<section id="view-events"');
const errorsViewStart = html.indexOf('<section id="view-errors"');
const handoffViewStart = html.indexOf('<section id="view-handoff"');
assert.ok(eventsViewStart >= 0 && errorsViewStart > eventsViewStart && handoffViewStart > errorsViewStart, 'events and errors pages should have stable inspector order');
assert.match(html.slice(eventsViewStart, errorsViewStart), /event-list/);
assert.doesNotMatch(html.slice(eventsViewStart, errorsViewStart), /error-list/);
assert.match(html.slice(errorsViewStart, handoffViewStart), /error-list/);
assert.doesNotMatch(html.slice(errorsViewStart, handoffViewStart), /event-list/);
assert.match(html, /class="system-monitor-card card-layer"[^>]*aria-label="System monitor"/);
assert.match(html, /class="system-monitor-metrics"/);
assert.match(html, /class="system-metric"/);
assert.match(html, /CPU/);
assert.match(html, /GPU/);
assert.match(html, /Memory/);
assert.match(html, /id="telemetry-state"[^>]*aria-live="polite"/);
assert.match(html, /id="cpu-value"[^>]*>—<\/strong>/);
assert.match(html, /id="gpu-value"[^>]*>—<\/strong>/);
assert.match(html, /id="memory-value"[^>]*>—<\/strong>/);
assert.doesNotMatch(html, /<strong>3\.7<small>%<\/small><\/strong>/);
assert.doesNotMatch(html, /<strong>38\.7<small>%<\/small><\/strong>/);
assert.equal((html.match(/class="system-metric"/g) || []).length, 3, 'system monitor should expose only three metrics');
assert.match(html, /class="system-runtime"[^>]*aria-label="Core runtime"/);
assert.match(html, /class="system-runtime-statuses"/);
assert.match(html, /class="system-runtime-details"/);
assert.match(html, /id="quality"/);
assert.match(html, /id="runtime-state"/);
assert.match(html, /id="quality" hidden/);
assert.match(html, /id="runtime-state" hidden/);
assert.doesNotMatch(html, /class="rail"/);
assert.doesNotMatch(html, /class="monitor"/);
assert.match(html, /class="avatar assistant-avatar"/);
assert.match(html, /class="response-time" hidden/);
assert.match(html, /id="core-status"/);
assert.match(html, /class="status offline"/);
assert.match(html, /id="ai-status"/);
assert.match(html, /for="prompt">Message JARVIS/);
assert.match(html, /aria-label="Send message"/);
assert.match(html, /id="prompt"[^>]*aria-keyshortcuts="Control\+L"/);
assert.match(html, /id="composer-hint"[^>]*class="composer-hint"[^>]*>Ctrl\+L focus</);
assert.doesNotMatch(html, /(?:src|href)=["']https?:\/\//i, 'renderer must not load remote resources');
assert.doesNotMatch(html, /<iframe|<webview/i);
assert.match(main, /nodeIntegration:\s*false/);
assert.match(main, /contextIsolation:\s*true/);
assert.match(main, /sandbox:\s*true/);
assert.match(main, /backgroundThrottling:\s*true/);
assert.match(main, /setPermissionRequestHandler/);
assert.match(main, /setPermissionCheckHandler/);
assert.match(main, /child-process-gone/);
assert.match(main, /setWindowOpenHandler/);
assert.match(main, /will-navigate/);
assert.match(main, /will-attach-webview/);
assert.match(main, /app\.whenReady\(\)/);
assert.match(main, /preloadPath/);
assert.match(main, /const windowTitle = selectedEdition === 'internal-test'/);
assert.match(main, /'JARVIS · 内测版'/);
assert.match(main, /'JARVIS · 开发版'/);
assert.match(main, /title: windowTitle/);
assert.match(main, /page-title-updated/);
assert.match(main, /window\.setTitle\(windowTitle\)/);
assert.match(main, /CoreSupervisor/);
assert.match(main, /requestedEdition = editionArg \? editionArg\.slice\('--edition='\.length\) : 'internal-test'/);
assert.match(main, /function createCoreSupervisor\(\)/);
assert.match(main, /app\.isPackaged/);
assert.match(main, /process\.resourcesPath/);
assert.match(main, /jarvis-core\.exe/);
assert.match(main, /coreExecutable/);
assert.match(main, /ensureReady\(\)/);
assert.match(main, /stopOwned\(\)/);
assert.match(main, /dialog\.showErrorBox/);
assert.match(main, /ipcMain\.handle\('jarvis-core-health'/);

const packageManifest = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
assert.equal(packageManifest.devDependencies?.['@openai/codex'], '0.153.2');
assert.equal(packageManifest.build?.nsis?.oneClick, false);
assert.equal(packageManifest.build?.nsis?.allowToChangeInstallationDirectory, true);
assert.deepEqual(packageManifest.build?.extraResources, [{ from: '../packaging/core-dist/jarvis-core', to: 'core' }]);
assert.match(main, /ipcMain\.handle\('jarvis-core-reconnect'/);
assert.match(main, /coreReconnectInFlight/);
assert.match(main, /function reconnectCore\(\)/);
assert.match(main, /coreSupervisor\.ensureReady\(\)/);
assert.match(main, /Boolean\(byId\('core-connection-checked'\)\)/);
assert.match(main, /ipcMain\.handle\('jarvis-core-telemetry'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-conversation-history'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-create-conversation'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-send-message'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-system-info'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-projects'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-project-git-status'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-project-list-files'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-project-read-file'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-project-search'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-project-refresh'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-obsidian-vaults'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-obsidian-connect'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-obsidian-disconnect'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-tasks'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-ai-mode'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-ai-check'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-ai-disconnect'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-ai-direct-config'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-speak-reply'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-speech-settings'/);
assert.match(main, /ipcMain\.handle\('jarvis-core-stop-speech'/);
assert.match(main, /ipcMain\.handle\('jarvis-runtime-settings-get'/);
assert.match(main, /ipcMain\.handle\('jarvis-runtime-settings-set'/);
assert.match(main, /require\('\.\/update-checker\.cjs'\)/);
assert.match(main, /ipcMain\.handle\('jarvis-update-check'/);
assert.match(main, /ipcMain\.handle\('jarvis-update-open'/);
assert.match(main, /shell\.openExternal\(latestUpdateUrl\)/);
assert.doesNotMatch(main, /shell\.openExternal\([^)]*payload/);
assert.match(main, /inspectorOpen/);
assert.match(main, /inspectorVisible/);
assert.match(main, /const corePage = document\.querySelector\('\[data-page="core"\]'\)/);
assert.match(main, /const coreVisible = coreView\.classList\.contains\('active'\)/);
assert.match(main, /chatAndCoreRemainVisible/);
assert.match(main, /inspectorClosed/);
assert.match(main, /floatingWindows/);
assert.match(main, /memoryVisible/);
assert.match(main, /knowledgeVisible/);
assert.match(main, /eventsVisible/);
assert.match(main, /errorsVisible/);
assert.match(main, /themeVisible/);
assert.doesNotMatch(main, /app\.setPath\(['"](?:userData|sessionData)/);
assert.doesNotMatch(main, /--disable-gpu|--in-process-gpu|use-angle|SwiftShader/i);

assert.match(supervisor, /CORE_HOST = '127\.0\.0\.1'/);
assert.match(supervisor, /CORE_PORT = 8765/);
assert.match(supervisor, /HEALTH_PATH = '\/api\/health'/);
assert.match(supervisor, /'-m', 'uvicorn', 'app\.api:app'/);
assert.match(supervisor, /shell: false/);
assert.match(supervisor, /windowsHide: true/);
assert.match(supervisor, /CREATE_NO_WINDOW/);
assert.match(supervisor, /CORE_PORT_OCCUPIED/);
assert.match(supervisor, /CORE_START_TIMEOUT/);
assert.match(supervisor, /stopOwned/);
assert.doesNotMatch(supervisor, /exec(?:File|Sync)?\s*\(|spawnSync\s*\(/);
assert.doesNotMatch(supervisor, /shell:\s*true/);
assert.doesNotMatch(supervisor, /--disable-gpu|--in-process-gpu|use-angle|SwiftShader/i);

assert.match(preload, /contextBridge\.exposeInMainWorld\('jarvisCore'/);
assert.match(preload, /contextBridge\.exposeInMainWorld\('jarvisUpdate'/);
assert.match(preload, /updateCheck: 'jarvis-update-check'/);
assert.match(preload, /updateOpen: 'jarvis-update-open'/);
assert.match(preload, /check: \(\) => invoke\(channels\.updateCheck\)/);
assert.match(preload, /open: \(\) => invoke\(channels\.updateOpen\)/);
assert.match(preload, /jarvis-core-health/);
assert.match(preload, /jarvis-core-reconnect/);
assert.match(preload, /reconnect: \(\) => invoke/);
assert.match(preload, /jarvis-core-telemetry/);
assert.match(preload, /jarvis-core-conversation-history/);
assert.match(preload, /jarvis-core-create-conversation/);
assert.match(preload, /jarvis-core-send-message/);
assert.match(preload, /jarvis-core-system-info/);
assert.match(preload, /jarvis-core-projects/);
assert.match(preload, /jarvis-core-project-git-status/);
assert.match(preload, /jarvis-core-project-list-files/);
assert.match(preload, /jarvis-core-project-read-file/);
assert.match(preload, /jarvis-core-project-search/);
assert.match(preload, /jarvis-core-project-refresh/);
assert.match(preload, /jarvis-core-obsidian-vaults/);
assert.match(preload, /jarvis-core-obsidian-connect/);
assert.match(preload, /obsidianConnect: \(config\) => invoke/);
assert.match(preload, /obsidianDisconnect: \(vaultId\) => invoke/);
assert.match(preload, /jarvis-core-tasks/);
assert.match(preload, /jarvis-core-ai-mode/);
assert.match(preload, /jarvis-core-ai-check/);
assert.match(preload, /jarvis-core-speak-reply/);
assert.match(preload, /jarvis-core-speech-settings/);
assert.match(preload, /jarvis-core-speech-voices/);
assert.match(preload, /jarvis-core-stop-speech/);
assert.match(preload, /speakReply: \(text, voice = null\) => invoke/);
assert.match(preload, /speechVoices: \(\) => invoke/);
assert.match(preload, /stopSpeech: \(\) => invoke/);
assert.match(preload, /aiCheck: \(\) => invoke/);
assert.match(preload, /sendMessage: \(message, conversationId, outputLanguage\)/);
assert.match(preload, /startChatStream: \(streamId, message, conversationId, outputLanguage\)/);
assert.match(preload, /ipcRenderer\.on\(channels\.chatStreamEvent/);
assert.doesNotMatch(preload, /ipcRenderer\.(send|sendSync|once|removeListener)/);
assert.doesNotMatch(preload, /process|require\(['"]node:/);

assert.match(bridge, /CORE_HOST = '127\.0\.0\.1'/);
assert.match(bridge, /CORE_PORT = 8765/);
assert.match(bridge, /path: '\/api\/health'/);
assert.match(bridge, /path: '\/api\/telemetry'/);
assert.match(bridge, /path: '\/api\/chat\/history'/);
assert.match(bridge, /path: '\/api\/chat\/session'/);
assert.match(bridge, /path: '\/api\/chat'/);
assert.match(bridge, /CHAT_STREAM_OPERATION/);
assert.match(bridge, /path: '\/api\/chat\/stream'/);
assert.match(bridge, /function streamCoreChat\(payload/);
assert.match(bridge, /const OUTPUT_LANGUAGES = new Set\(\['en', 'zh-CN'\]\)/);
assert.match(bridge, /output_language: outputLanguage/);
assert.match(bridge, /sendMessage: Object\.freeze\(\{ method: 'POST', path: '\/api\/chat', timeoutMs: CHAT_TIMEOUT_MS \}\)/);
assert.match(bridge, /path: '\/api\/system-info'/);
assert.match(bridge, /path: '\/api\/projects'/);
assert.match(bridge, /path: '\/api\/projects\/git-status'/);
assert.match(bridge, /path: '\/api\/projects\/list-files'/);
assert.match(bridge, /path: '\/api\/projects\/read-file'/);
assert.match(bridge, /path: '\/api\/projects\/search'/);
assert.match(bridge, /path: '\/api\/projects\/refresh'/);
assert.match(bridge, /path: '\/api\/obsidian\/vaults'/);
assert.match(bridge, /obsidianConnect: Object\.freeze\(\{ method: 'POST', path: '\/api\/obsidian\/vaults', timeoutMs: CORE_TIMEOUT_MS \}\)/);
assert.match(bridge, /function validateObsidianConnectPayload\(payload\)/);
assert.match(bridge, /path: '\/api\/tasks'/);
assert.match(bridge, /path: '\/api\/settings\/ai\/mode'/);
assert.match(bridge, /path: '\/api\/settings\/ai\/check'/);
assert.match(bridge, /timeoutMs: AI_CHECK_TIMEOUT_MS/);
assert.match(bridge, /Object\.freeze\(\{[\s\S]*health:[\s\S]*createConversation:[\s\S]*sendMessage:/);
assert.match(bridge, /SPEECH_OPERATIONS/);
assert.match(bridge, /path: '\/api\/system-speech'/);
assert.match(bridge, /path: '\/api\/system-speech\/synthesize'/);
assert.match(bridge, /path: '\/api\/system-speech\/settings'/);
assert.match(bridge, /path: '\/api\/system-speech\/voices'/);
assert.match(bridge, /path: '\/api\/system-speech\/stop'/);
assert.match(bridge, /function validateSpeechPayload\(payload\)/);
assert.match(bridge, /CORE_OPERATIONS\[operation\] \|\| SPEECH_OPERATIONS\[operation\]/);
assert.doesNotMatch(bridge, /https?:\/\//i);
assert.doesNotMatch(bridge, /--disable-gpu|--in-process-gpu|use-angle|SwiftShader/i);

assert.match(unified, /window\.jarvisCore/);
assert.match(unified, /window\.jarvisUpdate/);
assert.match(unified, /function checkForAppUpdate\(/);
assert.match(unified, /function openAppUpdate\(/);
assert.match(unified, /function dismissAppUpdate\(/);
assert.match(unified, /Update available/);
assert.match(unified, /setTimeout\(\(\) => void checkForAppUpdate\(\), 1200\)/);
assert.match(unified, /telemetryInFlight/);
assert.match(unified, /function applyTelemetry\(snapshot, error = null\)/);
assert.match(unified, /coreBridge\.telemetry\(\)/);
assert.match(unified, /function refreshHistory\(\)/);
assert.match(unified, /function refreshTasks\(\)/);
assert.match(unified, /function refreshProjects\(\)/);
assert.match(unified, /function refreshSystemInfo\(\)/);
assert.match(unified, /function refreshSpeechSettings\(\)/);
assert.match(unified, /function reconnectCoreFromUi\(\)/);
assert.match(unified, /coreBridge\.reconnect\(\)/);
assert.match(unified, /refreshHealth\(\{ manual: true \}\)/);
assert.match(unified, /UI\/Core version mismatch · close all JARVIS windows and reopen this shortcut\./);
assert.match(unified, /Saved chats are unavailable\./);
assert.match(unified, /status\.title = error \? detail : ''/);
assert.match(unified, /function obsidianVaultIdFor\(value\)/);
assert.match(unified, /function connectObsidianVault\(\)/);
assert.match(unified, /coreBridge\.obsidianConnect\(\{/);
assert.match(unified, /defaultAccess: 'excluded'/);
assert.match(unified, /Obsidian connection:/);
assert.match(unified, /function runProjectAction\(action\)/);
assert.match(unified, /'conversationHistory'/);
assert.match(unified, /'obsidianVaults'/);
assert.match(unified, /'tasks'/);
assert.match(unified, /'projects'/);
assert.match(unified, /coreBridge\.systemStatus\(\)/);
assert.match(unified, /renderDeviceBattery\(response\)/);
assert.match(unified, /coreBridge\.speechSettings\(\)/);
assert.match(unified, /coreBridge\.speechVoices\(\)/);
assert.match(unified, /coreBridge\.aiMode\(mode\)/);
assert.match(unified, /coreBridge\.aiCheck\(\)/);
assert.match(unified, /function refreshAiConnectionCheck\(\)/);
assert.match(unified, /AI transport check completed without an inference probe/);
assert.match(unified, /setInterval\(refreshTelemetry, 2000\)/);
assert.match(unified, /JarvisConversationStore\.create/);
assert.match(unified, /window\.JarvisComposerBehavior/);
assert.match(unified, /window\.JarvisAutoSpeech/);
assert.match(unified, /autoSpeechBehavior\.create/);
assert.match(unified, /window\.JarvisResponseStream/);
assert.match(unified, /new responseStreamBehavior\.StreamProjector/);
assert.match(unified, /new responseStreamBehavior\.SpeechChunker/);
assert.match(responseStream, /hasPendingText\(\)/);
assert.match(unified, /hasBufferedSpeech/);
assert.match(responseStream, /function detectSpeechLanguage\(/);
assert.match(responseStream, /function selectSpeechVoiceForText\(/);
assert.match(updateChecker, /UPDATE_API_URL = 'https:\/\/api\.github\.com\/repos\/Justin11-13\/JARVIS_Local_AI\/releases\?per_page=20'/);
assert.match(updateChecker, /RELEASE_ASSET_PATTERN/);
assert.match(updateChecker, /function compareVersions\(/);
assert.match(updateChecker, /function selectInternalTestRelease\(/);
assert.match(updateChecker, /function checkForUpdate\(/);
assert.match(updateChecker, /UPDATE_CHECK_TIMEOUT/);
assert.match(updateChecker, /github\.com/);
assert.match(unified, /function automaticSpeechVoiceForText\(/);
assert.match(unified, /function resolveStreamSpeechVoice\(/);
assert.match(unified, /void refreshSpeechVoices\(\)/);
assert.match(autoSpeech, /synthesize\(item\.text, item\.voiceId\)/);
assert.match(unified, /function consumeChatStream\(/);
assert.match(unified, /function handleChatStreamEvent\(/);
assert.match(unified, /coreBridge\.startChatStream\(/);
assert.match(unified, /responseLanguageStorageKey/);
assert.match(unified, /function resolveResponseLanguage\(\)/);
assert.match(unified, /function saveResponseLanguage\(value\)/);
assert.match(unified, /syncResponseLanguageSetting\(\)/);
assert.match(unified, /coreBridge\.cancelChatStream\(/);
assert.match(unified, /requestReceivedAt/);
assert.match(unified, /firstModelTokenAt/);
assert.match(unified, /firstTextRenderedAt/);
assert.match(unified, /firstSpeechChunkCreatedAt/);
assert.match(unified, /firstTtsAudioReadyAt/);
assert.match(unified, /firstAudioPlaybackAt/);
assert.match(unified, /responseCompletedAt/);
assert.match(unified, /stream_metrics/);
assert.match(unified, /window\.JarvisMarkdownRenderer/);
assert.match(unified, /const renderMarkdown = markdownRenderer\.render/);
assert.match(unified, /renderMarkdown\(paragraph, text\)/);
assert.match(unified, /renderMarkdown\(message\.paragraph, text\)/);
assert.match(unified, /const speechKey = `\$\{turn\.id\}:\$\{outcome\.awaiting \? 'confirmation' : 'reply'\}`/);
assert.match(unified, /autoSpeech\.enqueue\(speechKey, speechText, \{/);
assert.match(unified, /voiceId: automaticSpeechVoiceForText\(/);
assert.match(unified, /response\?\.speech/);
assert.match(unified, /const textReplyCompleted = outcome\.toolResults\.length === 0/);
assert.match(unified, /const shouldSpeak = \(outcome\.completed \|\| textReplyCompleted \|\| outcome\.awaiting\)/);
assert.match(unified, /const follow = force \|\| conversationFollowTail \|\| conversationAtBottom\(\)/);
const responseFunction = unified.match(/function renderChatResponse\(response, turn,[\s\S]*?\n}\n\nfunction updateComposerState/);
assert.ok(responseFunction, 'chat response renderer should remain explicit');
assert.ok(responseFunction[0].indexOf('autoSpeech.enqueue') < responseFunction[0].indexOf('updateTurnAssistant'), 'speech bridge should start before response DOM update');
assert.match(unified, /themeStorageKey = 'jarvis\.ui\.theme\.v1'/);
assert.match(unified, /customThemeStorageKey = 'jarvis\.ui\.theme\.custom\.v1'/);
assert.match(unified, /themePaletteFields = Object\.freeze/);
assert.match(unified, /function applyCustomThemeOverrides\(\)/);
assert.match(unified, /function saveCustomThemeColor\(key, value\)/);
assert.match(unified, /function resetCustomTheme\(\)/);
assert.match(unified, /data-theme-color/);
assert.match(unified, /themeLabels = Object\.freeze/);
assert.match(unified, /memory: \['Memory'/);
assert.match(unified, /knowledge: \['Knowledge'/);
assert.match(unified, /'memory', 'knowledge', 'theme', 'voice', 'events', 'errors'/);
const internalTestPagesMatch = unified.match(/const internalTestPages = new Set\(\[([\s\S]*?)\n\]\);/);
assert.ok(internalTestPagesMatch, 'internal-test page allowlist must remain explicit');
assert.match(internalTestPagesMatch[1], /'voice'/, 'Voice must remain available in internal-test edition');
assert.match(unified, /events: \['Events', 'Visible local lifecycle evidence\.'/);
assert.match(unified, /errors: \['Errors', 'Bridge and Core failures remain explicit\.'/);
assert.match(unified, /function renderEventList\(listId, records, emptyText\)/);
assert.match(unified, /function renderErrorRecords\(\)/);
assert.match(unified, /eventRecords\.filter\(\(record\) => record\.level !== 'error'\)/);
assert.match(unified, /eventRecords\.filter\(\(record\) => record\.level === 'error'\)/);
assert.match(unified, /function renderEventSurfaces\(\)/);
assert.match(unified, /if \(page === 'events' \|\| page === 'errors'\) renderEventSurfaces\(\);/);
assert.match(unified, /#errors-clear/);
assert.match(unified, /if \(eventRecords\[index\]\.level !== 'error'\) eventRecords\.splice\(index, 1\);/);
assert.match(unified, /if \(eventRecords\[index\]\.level === 'error'\) eventRecords\.splice\(index, 1\);/);
assert.match(unified, /theme: \['Theme'/);
assert.match(unified, /if \(page === 'memory'\) void refreshHistory\(\);/);
assert.match(unified, /if \(page === 'knowledge'\) void refreshVaults\(\);/);
assert.match(unified, /#obsidian-connect/);
assert.match(unified, /document\.documentElement\.dataset\.theme/);
assert.match(unified, /function syncThemeSetting\(\)/);
assert.match(unified, /function applyTheme\(value\)/);
assert.match(unified, /function syncCorePalette\(\)/);
assert.match(unified, /autoSpeech\.setEnabled/);
assert.match(unified, /coreBridge\.speakReply/);
assert.match(unified, /coreBridge\.synthesizeSpeech/);
assert.match(unified, /coreBridge\.stopSpeech/);
assert.doesNotMatch(unified, /speechSynthesis/i);
assert.match(unified, /composer\.requestSubmit\(\)/);
assert.match(unified, /compositionstart/);
assert.match(unified, /compositionend/);
assert.match(unifiedCss, /\.connection-actions \.full-row \{ grid-column: 1 \/ -1; \}/);
assert.match(unifiedCss, /\.connection-actions \.connection-field input \{/);
assert.match(unified, /isImeEnter\(event, compositionActive\)/);
assert.match(unified, /input\.disabled = pending/);
assert.match(unified, /isFocusShortcut\(event\)/);
assert.match(unified, /if \(modal\.classList\.contains\('open'\)\)/);
assert.match(unified, /focusInput\(composerInput\)/);
assert.match(unified, /dataset\.turnId = turn\.id/);
assert.match(unified, /conversationStore\.isCurrent\(turn\)/);
assert.match(unified, /conversationStore\.hasPendingConfirmation\(\)/);
assert.doesNotMatch(unified, /input\.disabled = busy \|\| pending/);
assert.match(unified, /input\.disabled = pending/);
assert.match(unified, /submit\.disabled = !coreOnline \|\| pending \|\| checkingAi/);
assert.match(unified, /draft is kept/);
assert.match(unified, /closest\('\.status'\)/);
assert.doesNotMatch(unified, /const blocked = !coreOnline \|\| sendInFlight \|\| pending/);
assert.match(unified, /requestAnimationFrame\(\(\) =>/);
assert.doesNotMatch(unified, /scrollIntoView/);
assert.match(unified, /data-confirm="?yes|dataset\.confirm = 'yes'/);
assert.match(unified, /data-confirm="?no|dataset\.confirm = 'no'/);
assert.match(unified, /conversationStorageKey/);
assert.match(unified, /conversationDayStorageKey/);
assert.match(unified, /function localDayKey\(value = new Date\(\)\)/);
assert.doesNotMatch(unified, /dailyRefresh|refreshConversationForDay|scheduleDailyConversationRefresh/);
assert.match(unified, /conversationStore\.newConversation\(\)/);
assert.match(unified, /JSON\.stringify\(eventRecords\)/);
assert.match(unified, /normalizedToolStatus\(item\?\.toolResult\) !== 'awaiting_confirmation'/);
assert.doesNotMatch(unified, /slice\(-80\)|eventRecords\.length > 24|toolResultRecords\.length > 80/);
assert.match(unified, /let conversationScrollFrame = 0/);
assert.match(unified, /let conversationFollowTail = true/);
assert.match(unified, /function cancelConversationScroll\(\)/);
assert.match(unified, /function scheduleConversationScroll\(\{ force = false \} = \{\}\)/);
assert.match(unified, /function scrollConversationToLatest\(\)/);
assert.match(unified, /conversationElement\.addEventListener\('scroll'/);
assert.match(unified, /cancelAnimationFrame\(conversationScrollFrame\)/);
assert.match(unified, /conversationElement\.scrollTo\(\{ top: conversationElement\.scrollHeight, behavior: 'auto' \}\)/);
assert.match(unified, /if \(conversationFollowTail\) scheduleConversationScroll\(\)/);
assert.match(unified, /appendConversationNode\(card, \{ force: true \}\)/);
assert.match(unified, /scheduleConversationScroll\(\{ force: true \}\)/);
assert.match(unifiedCss, /\.message-content/);
assert.match(unifiedCss, /\.message-content (?:ul|ol)/);
assert.match(unifiedCss, /\.message-content pre/);
assert.match(markdownRenderer, /function parse\(source\)/);
assert.match(markdownRenderer, /function render\(container, source\)/);
assert.doesNotMatch(markdownRenderer, /innerHTML/);
assert.match(markdownRenderer, /SAFE_LINK_PROTOCOLS/);
assert.match(unified, /function createJarvisAvatar\(\)/);
assert.match(unified, /const source = \$\('\.brand svg'\)/);
assert.match(unified, /if \(role !== 'user'\) article\.append\(createJarvisAvatar\(\)\)/);
assert.match(unified, /const card = document\.createElement\('details'\)/);
assert.match(unified, /const summary = document\.createElement\('summary'\)/);
assert.match(unified, /card\.open = status === 'awaiting_confirmation'/);
assert.match(unified, /card\.append\(summary, pre, meta\)/);
assert.match(unified, /if \(status === 'denied'\) return null/);
assert.match(unified, /const card = document\.createElement\('div'\)/);
assert.match(unified, /card\.className = 'confirmation-actions-only instrument'/);
assert.match(unified, /card\.setAttribute\('aria-label', 'Confirmation actions'\)/);
assert.match(unified, /turn\.confirmationCard = card/);
assert.match(unified, /function clearConfirmationCard\(turn\)/);
assert.match(unified, /clearConfirmationCard\(turn\)/);
const confirmationBranch = unified.match(/if \(status === 'awaiting_confirmation'\) \{[\s\S]*?\n  \}\n\n  \/\/ Terminal tool details belong to the dedicated Tool Results page\.[\s\S]*?\n  return null;\n\}/);
assert.ok(confirmationBranch, 'pending confirmation renderer should remain an actions-only branch');
assert.doesNotMatch(confirmationBranch[0], /JSON\.stringify|createElement\('pre'\)|createElement\('summary'\)/);
assert.match(confirmationBranch[0], /return null/);
assert.match(unified, /function setResponseTime\(message, elapsedMs\)/);
assert.match(unified, /Response time \$\{\(/);
assert.match(unified, /const requestStartedAt = performance\.now\(\)/);
assert.match(unified, /setResponseTime\(turn\.assistantMessage, performance\.now\(\) - requestStartedAt\)/);
assert.match(unified, /const checkingAi = surfaceInFlight\.has\('aiCheck'\)/);
assert.match(unified, /submit\.disabled = !coreOnline \|\| pending \|\| checkingAi/);
assert.match(unified, /surfaceInFlight\.add\('aiCheck'\);[\s\S]*updateComposerState\(\);/);
assert.match(unified, /surfaceInFlight\.delete\('aiCheck'\);[\s\S]*updateComposerState\(\);/);
assert.match(unified, /!options\.confirmationDecision && surfaceInFlight\.has\('aiCheck'\)/);
assert.match(unified, /conversationStore\.hasPendingConfirmation\(\)\n\s*\|\| surfaceInFlight\.has\('aiCheck'\)/);
assert.match(unified, /setInterval\(refreshHealth, 2000\)/);
assert.doesNotMatch(unified, /monitor:\s*\['System monitor'/);
assert.match(unified, /const panelOpen = page !== 'assistant'/);
assert.match(unified, /const panelIdleStorageKey = 'jarvis\.panel\.idle-seconds\.v1'/);
assert.match(unified, /const panelIdleOptions = Object\.freeze\(\[5, 10, 25, 30, 60, 0\]\)/);
assert.match(unified, /panelIdleSeconds === 0/);
assert.match(unified, /panelCloseTimer/);
assert.match(unified, /setTimeout\(\(\) => \{/);
assert.match(unified, /\.dock-zone'\)\?\.addEventListener\('pointerdown'/);
assert.match(unified, /\.page-stack'\)\?\.addEventListener\('scroll'/);
assert.match(unified, /capture: true/);
assert.match(unified, /const autoSpeechStorageKey = 'jarvis\.auto-speech\.enabled\.v1'/);
assert.match(unified, /const speechVoiceStorageKey = 'jarvis\.auto-speech\.voice\.v1'/);
assert.match(unified, /let installedSpeechVoices = \[\]/);
assert.match(unified, /let selectedSpeechVoiceId = readSpeechVoicePreference\(\)/);
assert.match(unified, /let currentSpeechVoiceName = ''/);
assert.match(unified, /function refreshSpeechVoices\(\)/);
assert.match(unified, /function previewSpeechVoice\(\)/);
assert.match(unified, /selectedSpeechVoiceForRequest\(\)/);
assert.match(unified, /coreBridge\.speechVoices/);
assert.match(unified, /coreBridge\.speakReply\('This is a Windows voice package preview\.', selectedSpeechVoiceForRequest\(\)\)/);
assert.match(unified, /function readAutoSpeechPreference\(\)/);
assert.match(unified, /function saveAutoSpeechPreference\(enabled\)/);
assert.match(unified, /const savedAutoSpeech = readAutoSpeechPreference\(\)/);
assert.match(unified, /autoSpeech\.setEnabled\(true\)/);
assert.match(unified, /saveAutoSpeechPreference\(enabled\)/);
assert.match(unified, /const motionStorageKey = 'jarvis\.motion\.low\.v1'/);
assert.match(unified, /function lowMotionEnabled\(\)/);
assert.match(unified, /lowMotionPreference = readLowMotionPreference\(\)/);
assert.match(unified, /const motionScale = lowMotionEnabled\(\) \? 0\.18 : 1/);
assert.match(unified, /return !paused && visible && !document\.hidden/);
assert.match(unified, /\.panel-view.*view\.classList\.toggle\('active'/s);
assert.match(unified, /inspectPanel|inspect-panel/);
assert.match(unified, /inspector\?\.toggleAttribute\('hidden', !panelOpen\)/);
assert.match(unified, /aria-hidden/);
assert.match(unified, /event\.key !== 'Escape'/);
assert.match(unified, /function refreshLocalClock\(\)/);
assert.match(unified, /const now = new Date\(\)/);
assert.match(unified, /clockLocaleStorageKey = 'jarvis\.clock\.locale\.v1'/);
assert.match(unified, /return localStorage\.getItem\(clockLocaleStorageKey\) === 'zh-CN' \? 'zh-CN' : 'en-US'/);
assert.match(unified, /new Intl\.DateTimeFormat\(resolveClockLocale\(\)/);
assert.match(unified, /setInterval\(refreshLocalClock, 1000\)/);
assert.doesNotMatch(unified, /visible && !document\.hidden && active === 'assistant'/);
assert.doesNotMatch(unified, /fetch\(|XMLHttpRequest|WebSocket|https?:\/\//i);
assert.match(composerBehavior, /function isImeEnter\(event, compositionActive = false\)/);
assert.match(composerBehavior, /event\?\.keyCode === 229/);
assert.match(composerBehavior, /function isFocusShortcut\(event\)/);
assert.match(composerBehavior, /event\.key\.toLowerCase\(\) === 'l'/);
assert.match(composerBehavior, /function focusInput\(input\)/);
assert.match(composerBehavior, /input\.setSelectionRange\(end, end\)/);
assert.match(autoSpeech, /enabled = false/);
assert.match(autoSpeech, /const seen = new Set\(\)/);
assert.match(autoSpeech, /let current = null/);
assert.match(autoSpeech, /let next = null/);
assert.match(autoSpeech, /const pending = \[\]/);
assert.match(autoSpeech, /maxQueued/);
assert.match(autoSpeech, /preparePromise/);
assert.match(autoSpeech, /generation \+= 1/);
assert.match(autoSpeech, /stop\(\)/);
assert.match(autoSpeech, /Automatic speech synthesis bridge is unavailable/);
assert.match(autoSpeech, /synthesize\(item\.text, item\.voiceId\)/);
assert.match(autoSpeech, /await play\(audio, item\)/);
assert.doesNotMatch(autoSpeech, /speechSynthesis/i);
assert.match(liveCss, /\.message\.from-user\s*\{[\s\S]*justify-content:\s*flex-end/);
assert.match(liveCss, /\.message\.from-user > div\s*\{[\s\S]*max-width|\.message\.from-user > div\s*\{/);
assert.match(liveCss, /\.message\.from-user p\s*\{[\s\S]*text-align:\s*left/);
assert.match(liveCss, /\.message \.assistant-avatar\s*\{/);
assert.match(liveCss, /\.response-time\s*\{/);
assert.match(liveCss, /\.live-tool-result > summary\s*\{/);
assert.match(liveCss, /\.live-tool-result\[open\] > summary\s*\{/);
assert.doesNotMatch(unifiedCss, /grid-template-columns:\s*var\(--chat-width\)\s+minmax\(0, 1fr\)\s+auto/);
assert.match(unifiedCss, /\.shell\s*\{[\s\S]*display:\s*block/);
assert.match(unifiedCss, /\.chat-pane\s*\{[\s\S]*position:\s*absolute/);
assert.match(unifiedCss, /--chat-height:\s*max\(470px, calc\(100dvh - var\(--monitor-height\) - var\(--chat-monitor-gap\) - 76px\)\)/);
assert.match(unifiedCss, /--monitor-height:\s*170px/);
assert.match(unifiedCss, /--chat-monitor-gap:\s*10px/);
assert.match(unifiedCss, /\.chat-pane\s*\{[\s\S]*height:\s*var\(--chat-height\)/);
assert.match(unifiedCss, /\.message\s*\{[\s\S]*grid-template-columns:\s*27px minmax\(0, 1fr\)/);
assert.match(unifiedCss, /\.message\s*\{[\s\S]*gap:\s*6px/);
assert.match(unifiedCss, /\.message\s*\{[\s\S]*padding:\s*8px 2px/);
assert.doesNotMatch(unifiedCss, /\.message\s*\{[^}]*border-bottom/);
assert.match(unifiedCss, /\.message\.from-user\s*\{[\s\S]*display:\s*flex[\s\S]*justify-content:\s*flex-end/);
assert.match(unifiedCss, /\.message\.from-user > div\s*\{[\s\S]*max-width:\s*min\(86%, 320px\)/);
assert.match(unifiedCss, /\.conversation\s*\{[\s\S]*overflow-x:\s*hidden/);
assert.match(unifiedCss, /\.conversation\s*\{[\s\S]*overflow-y:\s*auto/);
assert.match(unifiedCss, /\.conversation\s*\{[\s\S]*scrollbar-width:\s*none/);
assert.match(unifiedCss, /\.conversation\s*\{[\s\S]*-ms-overflow-style:\s*none/);
assert.match(unifiedCss, /\.conversation::\-webkit-scrollbar\s*\{[\s\S]*display:\s*none/);
assert.match(unifiedCss, /\.composer-hint\s*\{[\s\S]*font:\s*8px var\(--mono\)/);
assert.match(unifiedCss, /\.assistant-controls\s*\{[\s\S]*display:\s*none/);
assert.match(unifiedCss, /\.dock-zone\s*\{[\s\S]*position:\s*absolute/);
assert.match(unifiedCss, /--floating-top:\s*max\(36px, calc\(\(100dvh - var\(--chat-height\) - var\(--monitor-height\) - var\(--chat-monitor-gap\)\) \/ 2 - 40px\)\)/);
assert.match(unifiedCss, /\.dock-stack\s*\{[\s\S]*position:\s*relative/);
assert.match(unifiedCss, /\.chat-pane\s*\{[\s\S]*top:\s*var\(--floating-top\)/, 'Chat should use the shared top anchor');
assert.match(unifiedCss, /\.dock-zone\s*\{[\s\S]*top:\s*var\(--floating-top\)/, 'Pages should use the shared top anchor');
assert.doesNotMatch(unifiedCss, /\.core-stage::before\s*\{/, 'the stage grid overlay should be removed');
assert.doesNotMatch(unifiedCss, /--grid-rgb\b/);
assert.match(unifiedCss, /\.dock-zone\.panel-open\s+\.inspect-panel\s*\{/);
assert.match(unifiedCss, /\.inspect-panel\s*\{/);
assert.match(unifiedCss, /transform-origin:\s*right top/);
assert.match(unifiedCss, /\.inspect-panel\s*\{[\s\S]*position:\s*absolute/);
assert.match(unifiedCss, /\.action-dock\s*\{[\s\S]*border-radius:\s*18px/);
assert.match(unifiedCss, /\.inspect-panel\s*\{[\s\S]*border-radius:\s*18px/);
assert.match(unifiedCss, /\.inspect-panel\s*\{[\s\S]*top:\s*0/);
assert.match(unifiedCss, /\.inspect-panel\s*\{[\s\S]*height:\s*auto/);
assert.match(unifiedCss, /\.inspect-panel\s*\{[\s\S]*max-height:\s*calc\(100dvh - var\(--floating-top\) - var\(--dock-top-offset\) - var\(--dock-overlay-bottom-gap\)\)/);
assert.doesNotMatch(unifiedCss, /\.inspect-panel\s*\{[\s\S]*height:\s*min\(580px/);
assert.match(unifiedCss, /\.action-dock\s*\{[\s\S]*position:\s*absolute/);
assert.match(unifiedCss, /\.dock-zone:not\(\.pages-collapsed\)\s+\.action-dock\s*\{/);
assert.match(unifiedCss, /\.dock-zone\.pages-nav-open\s+\.inspect-panel\s*\{/);
assert.match(unifiedCss, /\.pages-toggle\s*\{/);
assert.match(unifiedCss, /\.pages-panel-toggle\s*\{/);
assert.match(unifiedCss, /-webkit-font-smoothing:\s*antialiased/);
assert.match(unifiedCss, /background-clip:\s*padding-box/);
assert.match(unifiedCss, /-webkit-backface-visibility:\s*hidden/);
assert.match(unifiedCss, /\.action-dock,\s*\.pages-toggle,[\s\S]*\.confirmation-actions-only\s*\{/);
assert.match(unifiedCss, /\.action-dock\s*\{[^}]*transform:\s*translateY\(-8px\)/);
assert.match(unifiedCss, /\.inspect-panel\s*\{[^}]*transform:\s*translateY\(-10px\)/);
const actionDockRule = unifiedCss.match(/\.action-dock\s*\{([\s\S]*?)\n\}/)?.[1] || '';
const inspectPanelRule = unifiedCss.match(/\.inspect-panel\s*\{([\s\S]*?)\n\}/)?.[1] || '';
assert.doesNotMatch(actionDockRule, /^\s*filter:\s*blur/m);
assert.doesNotMatch(inspectPanelRule, /^\s*filter:\s*blur/m);
assert.match(unifiedCss, /\.dock-nav button\s*\{[\s\S]*grid-template-rows:\s*auto auto/);
assert.match(unifiedCss, /\.dock-nav button\s*\{[\s\S]*min-height:\s*52px/);
assert.match(unifiedCss, /\.dock-nav\s*\{[\s\S]*grid-template-columns:\s*repeat\(5, minmax\(32px, 1fr\)\)/);
assert.match(unifiedCss, /@keyframes page-view-enter/);
assert.match(unifiedCss, /\.panel-view\.page-view-enter\s*\{/);
assert.match(unifiedCss, /@keyframes page-header-enter/);
assert.match(unifiedCss, /\.inspect-head\.page-header-enter\s*\{[\s\S]*animation:\s*page-header-enter\s*\.3s/);
assert.match(unifiedCss, /page-view-enter\s*\.36s/);
assert.match(unifiedCss, /@keyframes feature-nav-enter/);
assert.match(unifiedCss, /\.action-dock\.feature-nav-enter\s*\{[\s\S]*transition:\s*none[\s\S]*animation:\s*feature-nav-enter\s*\.34s/);
assert.match(unifiedCss, /@keyframes feature-page-enter/);
assert.match(unifiedCss, /\.inspect-panel\.feature-page-enter\s*\{[\s\S]*transition:\s*none[\s\S]*animation:\s*feature-page-enter\s*\.4s/);
assert.match(unifiedCss, /@keyframes conversation-restore/);
assert.match(unifiedCss, /\.conversation\.conversation-restore\s*\{/);
assert.match(unifiedCss, /\.conversation-row\.is-opening\s*\{/);
assert.match(unifiedCss, /--dock-overlay-bottom-gap:\s*24px/);
assert.match(unifiedCss, /--dock-top-offset:\s*0px/);
assert.match(unifiedCss, /\.nav-label\s*\{[\s\S]*position:\s*static[\s\S]*font:\s*600 8px\/1\.15 var\(--mono\)[\s\S]*white-space:\s*nowrap/);
assert.match(unifiedCss, /--dock-window:\s*min\(460px/);
assert.match(unifiedCss, /--dock-window:\s*min\(360px/);
assert.match(unifiedCss, /--dock-window:\s*min\(340px/);
assert.match(unifiedCss, /\.inspect-panel\s*\{[\s\S]*width:\s*100%/);
assert.match(unifiedCss, /\.history-actions\s*\{[\s\S]*max-width:\s*230px[\s\S]*flex-wrap:\s*nowrap/);
assert.match(unifiedCss, /\.dock-nav button::after\s*\{/);
assert.match(unifiedCss, /content:\s*attr\(aria-label\)/);
assert.match(unifiedCss, /\.page-stack\s*\{[\s\S]*display:\s*flex[\s\S]*flex-direction:\s*column[\s\S]*overflow:\s*hidden/);
assert.match(unifiedCss, /\.panel-view\s*\{[\s\S]*flex:\s*1 1 auto[\s\S]*height:\s*auto[\s\S]*max-height:\s*none[\s\S]*min-height:\s*0[\s\S]*overflow-y:\s*auto[\s\S]*padding:\s*24px 22px 30px/);
assert.match(unifiedCss, /\.panel-view\s*\{[\s\S]*scrollbar-gutter:\s*stable/);
assert.match(unifiedCss, /\.page-stack\s*\{[\s\S]*width:\s*100%/);
assert.match(unifiedCss, /\.panel-view\s*\{[\s\S]*width:\s*100%/);
assert.match(unifiedCss, /\.panel-view\s*> \* \+ \*\s*\{\s*margin-top:\s*16px/);
assert.match(unifiedCss, /\.instrument\s*\{[\s\S]*border-radius:\s*12px/);
assert.match(unifiedCss, /\.tool-result\s*\{[\s\S]*border-radius:\s*12px/);
assert.match(unifiedCss, /\.task-list\s*\{[\s\S]*border-radius:\s*12px/);
assert.match(unifiedCss, /\.settings-list\s*\{[\s\S]*border-radius:\s*12px/);
assert.match(unifiedCss, /\.composer\s*\{[\s\S]*height:\s*32px/);
assert.match(unifiedCss, /\.composer\s*\{[\s\S]*width:\s*calc\(100% - 20px\)[\s\S]*min-width:\s*0/);
assert.match(unifiedCss, /\.composer input\s*\{[\s\S]*width:\s*0[\s\S]*flex:\s*1 1 0/);
assert.match(unifiedCss, /\.composer-hint\s*\{[\s\S]*max-width:\s*38%[\s\S]*text-overflow:\s*ellipsis/);
assert.match(unifiedCss, /\.composer button\s*\{[\s\S]*width:\s*32px/);
assert.match(unifiedCss, /\.message p\s*\{[\s\S]*white-space:\s*normal[\s\S]*overflow-wrap:\s*anywhere/);
assert.match(unifiedCss, /\.core-stage\s*\{[\s\S]*display:\s*flex[\s\S]*min-width:\s*0/);
assert.match(unifiedCss, /\.core-space canvas\s*\{[\s\S]*width:\s*100%[\s\S]*max-width:\s*100%[\s\S]*min-width:\s*0/);
assert.match(unifiedCss, /\.settings-list\s*\{/);
assert.match(unifiedCss, /\.setting-row\s*\{[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\) auto/);
assert.match(unifiedCss, /\.setting-toggle input:checked \+ \.toggle-track/);
assert.match(unifiedCss, /\.setting-toggle input:focus-visible \+ \.toggle-track/);
assert.match(unifiedCss, /\.settings-status\s*\{/);
assert.match(unifiedCss, /:root\[data-theme="cyan"\]/);
assert.match(unifiedCss, /:root\[data-theme="violet"\]/);
assert.match(unifiedCss, /:root\[data-theme="matrix"\]/);
assert.match(unifiedCss, /--core-color-a:\s*#ff6e05/);
assert.match(unifiedCss, /--core-color-b:\s*#ffbf4d/);
assert.match(unifiedCss, /--core-color-a:\s*#00c8e7/);
assert.match(unifiedCss, /--core-color-a:\s*#7a3cff/);
assert.match(unifiedCss, /--core-color-a:\s*#00d978/);
assert.match(unifiedCss, /\.theme-palette-grid\s*\{/);
assert.match(unifiedCss, /\.theme-color-control input\[type="color"\]/);
assert.match(unifiedCss, /\.theme-color-control:focus-within/);
assert.match(unifiedCss, /\.system-monitor-card\s*\{[\s\S]*position:\s*absolute/);
assert.match(unifiedCss, /\.system-monitor-card\s*\{[\s\S]*top:\s*calc\(var\(--floating-top\) \+ var\(--chat-height\) \+ var\(--chat-monitor-gap\)\)/);
assert.match(unifiedCss, /\.system-monitor-card\s*\{[\s\S]*left:\s*var\(--floating-gap\)/);
assert.match(unifiedCss, /\.system-monitor-card\s*\{[\s\S]*width:\s*min\(var\(--chat-width\), calc\(100vw - 40px\)\)/);
assert.match(unifiedCss, /\.system-monitor-card\s*\{[\s\S]*height:\s*auto/);
assert.match(unifiedCss, /\.system-monitor-card\s*\{[\s\S]*min-height:\s*0/);
assert.match(unifiedCss, /\.system-monitor-card\s*\{[\s\S]*margin-top:\s*0/);
assert.match(unifiedCss, /\.system-monitor-card\s*\{[\s\S]*bottom:\s*auto/);
assert.match(unifiedCss, /\.system-monitor-card\s*\{[\s\S]*transform:\s*none/);
assert.match(unifiedCss, /\.system-monitor-card\s*\{[\s\S]*transform-origin:\s*initial/);
assert.doesNotMatch(unifiedCss, /\.dock-zone\.panel-open\s+\.system-monitor-card/);
assert.match(unifiedCss, /@media \(max-height:\s*760px\)[\s\S]*--floating-top:\s*max\(28px, calc\(\(100dvh - var\(--chat-height\) - var\(--monitor-height\) - var\(--chat-monitor-gap\)\) \/ 2 - 34px\)\)/);
assert.match(unifiedCss, /--core-height:\s*clamp\(390px, 56vh, 600px\)/);
assert.match(unifiedCss, /@media \(max-height:\s*760px\)[\s\S]*--core-height:\s*min\(400px, max\(300px, calc\(100dvh - 330px\)\)\)/);
assert.match(unifiedCss, /@media \(max-height:\s*760px\)[\s\S]*--chat-height:\s*min\(400px, calc\(100dvh - 300px\)\)/);
assert.match(unifiedCss, /\.system-monitor-metrics\s*\{[\s\S]*grid-template-columns:\s*repeat\(3/);
assert.match(unifiedCss, /\.system-runtime\s*\{[\s\S]*border-top:\s*1px solid var\(--line-soft\)/);
assert.match(unifiedCss, /\.system-runtime-statuses\s*\{[\s\S]*grid-template-columns:\s*repeat\(2/);
assert.match(unifiedCss, /\.system-runtime-details\s*\{[\s\S]*grid-template-columns:\s*64px/);
assert.match(unifiedCss, /\.core-layer\s*\{/);
assert.match(unifiedCss, /\.card-layer\s*\{/);
assert.doesNotMatch(unifiedCss, /\.monitor-view\b|\.monitor-heading\b/);
assert.doesNotMatch(unifiedCss, /\.chat-head\s*\{[^}]*border-bottom/);
assert.doesNotMatch(unifiedCss, /\.core-head\s*\{[^}]*border-bottom/);
assert.doesNotMatch(unifiedCss, /\.dock-head\s*\{[^}]*border-bottom/);
assert.doesNotMatch(unifiedCss, /\.inspect-head\s*\{[^}]*border-bottom/);
assert.match(unifiedCss, /prefers-reduced-motion:\s*reduce/);
assert.doesNotMatch(unifiedCss, /--disable-gpu|--in-process-gpu|use-angle|SwiftShader/i);
assert.match(hologram, /uniform vec3 coreColorA/);
assert.match(hologram, /uniform vec3 coreColorB/);
assert.match(hologram, /setPalette\(first,second\)/);
assert.match(hologram, /gl\.uniform3fv\(u\.coreColorA/);
assert.match(hologram, /gl\.uniform3fv\(u\.coreColorB/);
assert.doesNotMatch(hologram, /p\.x\s*-?=\s*\.13/);
assert.match(hologram, /if\(bridge\)p=mix\(p,vec3\(0\.,0\.,0\.\),detail\.z\)/);
assert.match(supervisor, /START_TIMEOUT_MS = 30000/);
assert.match(main, /requestSingleInstanceLock\(\)/);
assert.match(main, /app\.setName\(appName\)/);
assert.match(main, /setLoginItemSettings\(/);
assert.match(main, /backgroundStart/);
assert.match(main, /window\.hide\(\)/);
assert.match(preload, /jarvis-runtime-settings-get/);
assert.match(preload, /jarvis-runtime-settings-set/);
assert.match(preload, /updateRuntimeSettings/);
assert.match(conversationStore, /success === true/);
assert.match(conversationStore, /success === null && topLevelStatus === 'awaiting_confirmation'/);
assert.match(conversationStore, /session_busy/);
assert.match(conversationStore, /confirmationInFlight/);
assert.match(conversationStore, /turn\.epoch === epoch/);
assert.match(conversationStore, /turns\.clear\(\)/);
assert.match(unified, /function openStoredConversation\(id\b/);
assert.match(unified, /function startNewConversation\(\)/);
assert.match(unified, /Every Electron launch starts a fresh active chat/);
assert.match(unified, /function refreshRuntimeSettings\(\)/);
assert.match(unified, /updateRuntimeSetting\('backgroundRunning'/);
assert.match(unified, /updateRuntimeSetting\('startOnLogin'/);
assert.doesNotMatch(unified, /void restoreActiveConversation\(\)/);
assert.doesNotMatch(conversationStore, /localStorage|sessionStorage|fetch\(|XMLHttpRequest|WebSocket|https?:\/\//i);

console.log(JSON.stringify({
  verification: 'passed',
  scope: 'static-electron-shell',
  rendererFiles: requiredFiles,
  coreBridge: 'fixed-loopback-ipc',
  coreStartup: 'bounded-owned-loopback-supervisor',
  coreConnection: 'health-refresh-and-bounded-supervisor-reconnect',
  conversationPersistence: 'per-conversation-local-core-storage-and-opaque-renderer-id',
  dailyConversationRotation: 'fresh-launch-explicit-history-and-start-new-chat',
  chatCard: 'compact-no-manual-new-conversation',
  pages: 'memory-and-knowledge-separated-events-and-errors-theme-entry',
  pagesLauncher: 'collapsed-toggle-expanded-five-column-grid',
  pagesLayout: 'content-fit-card-with-shared-top-anchor-viewport-cap-and-bottom-gap',
  knowledgeConnection: 'explicit-register-disconnect-reconnect',
  settings: 'local-date-panel-auto-close-auto-speech-low-motion-and-runtime-lifecycle',
  automaticAiCheck: 'managed-handshake-on-core-ready-no-inference',
  themePresets: 'amber-cyan-violet-matrix-custom-overrides',
  speechTiming: 'streaming-text-chunked-tts-current-next',
  automaticSpeech: 'opt-in-selected-windows-system-voice-no-manual-buttons',
  speechVoicePackages: 'runtime-listed-windows-onecore-voices-with-explicit-preview',
  motion: 'low-motion-slows-core-without-stopping-rotation',
  externalRuntimeResources: false,
  rendererNodeSurface: 'none',
}));
